### ISSUE TITLE
Question with HEOM.py

### ISSUE THREAD

**Issue by XinyiJi1** [KacperKubara/heterogeneous_dist_metrics#14] opened 2020-08-04 05:54 UTC
Hi, I met some problems when I tried to use the HEOM library with both numeric and categorical data. I feel the problem is the following: 
`# Get the normalization scheme for numerical variables
if normalised == "std":
    self.range = 4* np.nanstd(X, axis = 0) 
else:
    self.range = np.nanmax(X, axis = 0) - np.nanmin(X, axis = 0)`
Seems like the above code can not work well with categorical data (especially for np.nanmin() function).

**Comment by KacperKubara** [comment] 2020-08-04 06:15
Probably a duplicate of https://github.com/KacperKubara/distython/issues/5?

**Comment by XinyiJi1** [comment] 2020-08-04 07:16
> Probably a duplicate of #5?

Oh! I found it! Thank you! :)

**Closed as completed** 2020-08-04 07:20 UTC
